### ISSUE TITLE
"Non-standard MQTT options" documents message_size_limit instead of max_message_size

### ISSUE THREAD

**Issue by okofish** [vernemq/vmq-docs#21]
The page at https://docs.vernemq.com/configuration/nonstandard documents the `message_size_limit` option, but that option is [deprecated](https://github.com/vernemq/vernemq/blob/982724b99c70116f05373ff2acbb0a527cbe73d4/apps/vmq_server/priv/vmq_server.schema#L286):

```
[warning] message_size_limit is deprecated and has no effect, use max_message_size instead
```

**Comment by larshesel** [comment]
Thanks for pointing it out. I've just pushed a fix!
