### ISSUE TITLE
Config for using SSL with postgres is wrong

### ISSUE THREAD

**Issue by fung** [vernemq/vmq-docs#37]
The doc stated `vmq_diversity.postgres.enabled`, however it should be `vmq_diversity.postgres.ssl` at https://docs.vernemq.com/configuration/db-auth

**Comment by ioolkos** [comment]
@fung oh, ok, thanks for reporting.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
