### ISSUE TITLE
bcrypt version should be more explicitly indicated

### ISSUE THREAD

**Issue by tonimore** [vernemq/vmq-docs#39]
At the moment, information about supported bcrypt version
_currently bcrypt version 2a (prefix $2a$) is supported._
specified at the bottom of the page, but it looks as it located in the Redis section. 
So, for example, If you need Mongo configuration you will read whole page, but skip Redis section, because you don't need it. And you never know that version $2b$ is not supported!
But Python implementation of the bcrypt use version $2b$ by default and for a first time it difficult to figure out why authorisation doesn't work. 
I think you need to move information about supported bcrypt version to the section: **Password verification and hashing methods**

**Comment by ioolkos** [comment]
@tonimore, thank you for your suggestion; I appreciate your feedback. I'm looking for ways to improve docs, in general. (Github/Gitbook integration is a problem currently)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by ioolkos** [comment]
@tonimore I moved the note as per your observation. Thanks again!

**Comment by tonimore** [comment]
> @tonimore I moved the note as per your observation. Thanks again!

Hello! I've just checked - loos like note:
**Note, currently bcrypt version 2a (prefix $2a$) is supported.**
still at the bottom of the page.
