### ISSUE TITLE
Proper build documentation missing

### ISSUE THREAD

**Issue by markandpathak** [vernemq/vmq-docs#47]
Recently for the latest version of vernemq, pre-compiled binaries will be available only to github sponsors. I respect that as the decision is required to generate revenue. But for community member please provide a detailed build documentation. Currently there is no build documentation on the official documentation site. On github all the documentation says is that we need Erlang/OTP and libsnappy-dev and we need to run `make rel`. And that's pretty much all of it.

So far with that documentation, I could only compile on a ubuntu machine. I could not compile it for alpine or debian-slim images as no list of dependencies provided.

Expected Documentation:
The documentation should mention the complete list of the dependencies with versions for different platforms.  For example there is no mention on how to compile vernemq for Alpine if we want to create a custom docker image as Dockerfile on github downloads the binaries itself instead of building the code.

**Comment by ioolkos** [comment]
@markandpathak thanks, yes, `make rel` is pretty much all of it. The rest is up to users preferences.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
