### ISSUE TITLE
metrics equivalent for cluster overview information in status page

### ISSUE THREAD

**Issue by andrewsaputra** [vernemq/vmq-docs#50]
Currently trying to stream metrics information from localhost:8888/metrics, however i couldn't find a clear documentation on which metrics correspond to cluster overview information in the status page, e.g.: Cluster Size, Clients Online / Offline.

![image](https://user-images.githubusercontent.com/18243701/192711806-34161eae-cde0-478f-b8f3-9053a015497c.png)

**Comment by ioolkos** [comment]
@andrewsaputra The status page does its own preparation of those metrics.

For details, you can look at the Javascript that pulls the data from "http://127.0.0.1:8888/status.json".

https://github.com/vernemq/vernemq/blob/master/apps/vmq_server/priv/static/js/status.js

The internal preparation for those metrics happens here:

https://github.com/vernemq/vernemq/blob/bffc2ec02f96ce8a2eb99c2d63056ead2a252714/apps/vmq_server/src/vmq_status_http.erl

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
